//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 06:53:26 PM CET 
//


package com.silvionetto.budget.xjb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.silvionetto.budget.xjb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _BudgetCategory_QNAME = new QName("", "BudgetCategory");
    private final static QName _BudgetSubCategory_QNAME = new QName("", "BudgetSubCategory");
    private final static QName _Store_QNAME = new QName("", "Store");
    private final static QName _Transaction_QNAME = new QName("", "Transaction");
    private final static QName _Balance_QNAME = new QName("", "Balance");
    private final static QName _Budget_QNAME = new QName("", "Budget");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.silvionetto.budget.xjb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link BudgetCategory }
     * 
     */
    public BudgetCategory createBudgetCategory() {
        return new BudgetCategory();
    }

    /**
     * Create an instance of {@link BudgetSubCategory }
     * 
     */
    public BudgetSubCategory createBudgetSubCategory() {
        return new BudgetSubCategory();
    }

    /**
     * Create an instance of {@link Store }
     * 
     */
    public Store createStore() {
        return new Store();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link Balance }
     * 
     */
    public Balance createBalance() {
        return new Balance();
    }

    /**
     * Create an instance of {@link Budget }
     * 
     */
    public Budget createBudget() {
        return new Budget();
    }

    /**
     * Create an instance of {@link BaseEntity }
     * 
     */
    public BaseEntity createBaseEntity() {
        return new BaseEntity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BudgetCategory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BudgetCategory }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BudgetCategory")
    public JAXBElement<BudgetCategory> createBudgetCategory(BudgetCategory value) {
        return new JAXBElement<BudgetCategory>(_BudgetCategory_QNAME, BudgetCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BudgetSubCategory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BudgetSubCategory }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BudgetSubCategory")
    public JAXBElement<BudgetSubCategory> createBudgetSubCategory(BudgetSubCategory value) {
        return new JAXBElement<BudgetSubCategory>(_BudgetSubCategory_QNAME, BudgetSubCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Store }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Store }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Store")
    public JAXBElement<Store> createStore(Store value) {
        return new JAXBElement<Store>(_Store_QNAME, Store.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Transaction")
    public JAXBElement<Transaction> createTransaction(Transaction value) {
        return new JAXBElement<Transaction>(_Transaction_QNAME, Transaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Balance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Balance }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Balance")
    public JAXBElement<Balance> createBalance(Balance value) {
        return new JAXBElement<Balance>(_Balance_QNAME, Balance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Budget }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Budget }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Budget")
    public JAXBElement<Budget> createBudget(Budget value) {
        return new JAXBElement<Budget>(_Budget_QNAME, Budget.class, null, value);
    }

}
