CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    login VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE budget_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE budget_sub_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES budget_category (id)
);

CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    sub_category_id BIGINT REFERENCES budget_sub_category (id)
);

CREATE TABLE budget_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    store_id BIGINT REFERENCES store (id),
    account VARCHAR(255) NOT NULL,
    contra_account VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    debit_credit VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    transaction_type VARCHAR(255) NOT NULL,
    notifications VARCHAR(512) NOT NULL,
    sub_category_id BIGINT REFERENCES budget_sub_category (id)
);

CREATE TABLE balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    opening_balance DOUBLE PRECISION NOT NULL
);

CREATE TABLE uploaded_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    owner_email VARCHAR(320) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    content BYTEA NOT NULL
);

CREATE INDEX idx_budget_sub_category_category_id
    ON budget_sub_category (category_id);

CREATE INDEX idx_store_sub_category_id
    ON store (sub_category_id);

CREATE INDEX idx_budget_transactions_store_id
    ON budget_transactions (store_id);

CREATE INDEX idx_budget_transactions_sub_category_id
    ON budget_transactions (sub_category_id);

CREATE INDEX idx_uploaded_documents_owner_email
    ON uploaded_documents (owner_email);
