ALTER TABLE uploaded_documents
    ALTER COLUMN content DROP NOT NULL;

ALTER TABLE uploaded_documents
    ADD COLUMN source_file_available BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE bank_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    uploaded_document_id BIGINT NOT NULL REFERENCES uploaded_documents (id),
    row_number INTEGER NOT NULL,
    date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    store_name VARCHAR(255) NOT NULL,
    account VARCHAR(255) NOT NULL,
    contra_account VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    debit_credit VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    transaction_type VARCHAR(255) NOT NULL,
    notifications VARCHAR(512) NOT NULL,
    CONSTRAINT uk_bank_movement_document_row UNIQUE (uploaded_document_id, row_number)
);

CREATE INDEX idx_bank_movement_uploaded_document_id
    ON bank_movement (uploaded_document_id);
